In [1]:
import numpy as np

01. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
array = np.arange(0,10)
print(array)
array = np.array(range(10))
print(array)
array = np.linspace(0,9, num=10, dtype=int)
print(array)
array = np.asarray(range(0,10))
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


02. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
array_zero = np.zeros((3,3))
print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


03. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
array = np.random.randint(0, 10, (5,5))
print(array)

[[1 4 4 6 5]
 [0 1 0 6 3]
 [4 9 4 0 2]
 [0 8 6 1 2]
 [8 9 1 1 5]]


04. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
array = np.random.rand(4,4)
print(array)

[[0.35060131 0.26881356 0.3894522  0.91854451]
 [0.41502546 0.97822861 0.57565578 0.96719295]
 [0.26037125 0.69092044 0.51900921 0.48136417]
 [0.5716305  0.37236515 0.90089671 0.73565878]]


05. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
array_one = np.random.randint(1, 10, 5)
array_two = np.random.randint(1, 10, 5)
print(array_one, array_two)

[2 3 6 9 6] [2 8 7 3 5]


In [7]:
# Add 

print(array_one + array_two)

[ 4 11 13 12 11]


In [8]:
# Subtraction

print(array_one - array_two)

[ 0 -5 -1  6  1]


In [9]:
# Multiplication

print(array_one * array_two)


[ 4 24 42 27 30]


In [10]:
# Devision

print(array_one / array_two)

[1.         0.375      0.85714286 3.         1.2       ]


06. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [11]:
array_one = np.random.randint(1, 100, 7)
array_two = np.random.randint(1, 100, 7)
print(array_one, array_two)

print(list(zip(array_one, array_two)))

[ 4 69 35 47 44 33  1] [12 87 24 36 67 39 83]
[(4, 12), (69, 87), (35, 24), (47, 36), (44, 67), (33, 39), (1, 83)]


In [12]:
#
scalar = np.sum(array_one *array_two)
print(scalar)

np.dot(array_one, array_two)

12901


12901

07. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [13]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,3))

print(matrix_one, matrix_two)

[[2 7]
 [1 7]] [[1 4 1]
 [3 4 2]]


In [14]:
np.dot(matrix_one, matrix_two)

array([[23, 36, 16],
       [22, 32, 15]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [15]:
matrix = np.random.randint(1, 10, (3,3))
print(matrix)

[[4 6 7]
 [7 5 8]
 [8 2 6]]


In [16]:
np.linalg.inv(matrix)

array([[ 2.33333333, -3.66666667,  2.16666667],
       [ 3.66666667, -5.33333333,  2.83333333],
       [-4.33333333,  6.66666667, -3.66666667]])

09. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [17]:
matrix = np.random.rand(4,4)
print(matrix)

[[0.22529664 0.79233769 0.55385578 0.10731558]
 [0.10359205 0.65914064 0.74207153 0.64832638]
 [0.35342823 0.54094473 0.82568263 0.82415341]
 [0.4986664  0.07881867 0.92989255 0.65855888]]


In [18]:
matrix.T

array([[0.22529664, 0.10359205, 0.35342823, 0.4986664 ],
       [0.79233769, 0.65914064, 0.54094473, 0.07881867],
       [0.55385578, 0.74207153, 0.82568263, 0.92989255],
       [0.10731558, 0.64832638, 0.82415341, 0.65855888]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [19]:
matrix = np.random.randint(1, 10, (3,4))
vector = np.random.randint(1, 10, 4)
print(matrix, vector)

[[3 2 2 9]
 [9 5 8 4]
 [3 1 1 7]] [5 3 1 5]


In [20]:
matrix.dot(vector)

array([68, 88, 54])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [21]:
matrix = np.random.rand(2,3)
vector = np.random.rand(3)
print(matrix, vector)

[[0.55579016 0.62434124 0.57124318]
 [0.89887386 0.5160109  0.01737263]] [0.68913198 0.47222898 0.34992091]


In [22]:
matrix.dot(vector)

array([0.87773473, 0.86919707])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [23]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[1 2]
 [7 7]] [[9 7]
 [6 5]]


In [24]:
matrix_one*matrix_two

array([[ 9, 14],
       [42, 35]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [25]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[8 7]
 [3 9]] [[6 4]
 [5 2]]


In [26]:
matrix_one.dot(matrix_two)

array([[83, 46],
       [63, 30]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [27]:
matrix = np.random.randint(1, 100, (5,5))
print(matrix)

[[ 1 73  6 86 83]
 [40 92 57 13 71]
 [60 85 97 58 80]
 [31 60 89 68 22]
 [59 53 60 33 81]]


In [28]:
matrix.sum()

1458

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [29]:
matrix_one = np.random.randint(1, 10, (4,4))
matrix_two = np.random.randint(1, 10, (4,4))
print(matrix_one, matrix_two)

[[3 7 4 4]
 [1 5 2 1]
 [6 8 4 3]
 [3 6 2 7]] [[5 8 6 6]
 [6 3 8 8]
 [5 3 5 9]
 [5 7 6 1]]


In [30]:
matrix_one-matrix_two

array([[-2, -1, -2, -2],
       [-5,  2, -6, -7],
       [ 1,  5, -1, -6],
       [-2, -1, -4,  6]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [31]:
matrix = np.random.rand(3,3)
print(matrix)

[[0.66856502 0.69647966 0.14053685]
 [0.48625344 0.30039452 0.42519005]
 [0.18231214 0.29264392 0.8298105 ]]


In [32]:
matrix.shape[0]

3

In [33]:
np.array([matrix[i].sum() for i in range(matrix.shape[0])]).reshape(matrix.shape[0],1)

array([[1.50558154],
       [1.211838  ],
       [1.30476656]])

In [34]:
matrix.sum(axis=1, keepdims=True)

array([[1.50558154],
       [1.211838  ],
       [1.30476656]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [35]:
matrix = np.random.randint(1, 100, (3,4))
print(matrix)

[[79 79 44 26]
 [ 6 11 96 93]
 [42  1 20 93]]


In [36]:
np.square(matrix)

array([[6241, 6241, 1936,  676],
       [  36,  121, 9216, 8649],
       [1764,    1,  400, 8649]])

In [37]:
matrix*matrix

array([[6241, 6241, 1936,  676],
       [  36,  121, 9216, 8649],
       [1764,    1,  400, 8649]])

In [38]:
np.power(matrix, 2)

array([[6241, 6241, 1936,  676],
       [  36,  121, 9216, 8649],
       [1764,    1,  400, 8649]], dtype=int32)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [39]:
vector = np.random.randint(1, 50, 4)
print(vector)

[36 22 31 32]


In [40]:
np.sqrt(vector)

array([6.        , 4.69041576, 5.56776436, 5.65685425])

In [41]:
np.power(vector, 1/2)

array([6.        , 4.69041576, 5.56776436, 5.65685425])