In [108]:
import numpy as np

01. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [109]:
array = np.arange(0,10)
print(array)
array = np.array(range(10))
print(array)
array = np.linspace(0,9, num=10, dtype=int)
print(array)
array = np.asarray(range(0,10))
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


02. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [110]:
array_zero = np.zeros((3,3))
print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


03. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [111]:
array = np.random.randint(0, 10, (5,5))
print(array)

[[8 8 2 1 3]
 [1 4 7 2 8]
 [9 7 5 0 9]
 [6 2 1 4 8]
 [1 9 9 3 0]]


04. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [112]:
array = np.random.rand(4,4)
print(array)

[[0.79297465 0.11498261 0.93445597 0.36249033]
 [0.45205761 0.30765146 0.43133946 0.36988572]
 [0.77945974 0.43854301 0.70531412 0.49434748]
 [0.70842764 0.3378957  0.57988634 0.55998519]]


05. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [113]:
array_one = np.random.randint(1, 10, 5)
array_two = np.random.randint(1, 10, 5)
print(array_one, array_two)

[9 3 1 1 4] [6 7 8 5 5]


In [114]:
# Add 

print(array_one + array_two)

[15 10  9  6  9]


In [115]:
# Subtraction

print(array_one - array_two)

[ 3 -4 -7 -4 -1]


In [116]:
# Multiplication

print(array_one * array_two)


[54 21  8  5 20]


In [117]:
# Devision

print(array_one / array_two)

[1.5        0.42857143 0.125      0.2        0.8       ]


06. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [118]:
array_one = np.random.randint(1, 100, 7)
array_two = np.random.randint(1, 100, 7)
print(array_one, array_two)

print(list(zip(array_one, array_two)))

[85 38 75 48  6 87 42] [44 65  4 44 92 15 83]
[(85, 44), (38, 65), (75, 4), (48, 44), (6, 92), (87, 15), (42, 83)]


In [119]:
#
scalar = np.sum(array_one *array_two)
print(scalar)

np.dot(array_one, array_two)

13965


13965

07. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [120]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,3))

print(matrix_one, matrix_two)

[[5 9]
 [6 5]] [[6 1 5]
 [7 7 4]]


In [121]:
np.dot(matrix_one, matrix_two)

array([[93, 68, 61],
       [71, 41, 50]])

08 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [122]:
matrix = np.random.randint(1, 10, (3,3))
print(matrix)

[[2 3 3]
 [6 4 4]
 [3 9 9]]


In [123]:
np.linalg.inv(matrix)

LinAlgError: Singular matrix

09. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix = np.random.rand(4,4)
print(matrix)

[[0.99681567 0.36130415 0.83009963 0.85066114]
 [0.43535906 0.81279665 0.61020555 0.34119939]
 [0.47255901 0.73885711 0.49732243 0.51635776]
 [0.31922043 0.44137705 0.7386625  0.36461361]]


In [ ]:
matrix.T

array([[0.99681567, 0.43535906, 0.47255901, 0.31922043],
       [0.36130415, 0.81279665, 0.73885711, 0.44137705],
       [0.83009963, 0.61020555, 0.49732243, 0.7386625 ],
       [0.85066114, 0.34119939, 0.51635776, 0.36461361]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.randint(1, 10, (3,4))
vector = np.random.randint(1, 10, 4)
print(matrix, vector)

[[2 6 2 8]
 [3 1 5 5]
 [4 6 5 6]] [8 2 5 7]


In [ ]:
matrix.dot(vector)

array([ 94,  86, 111])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.rand(2,3)
vector = np.random.rand(3)
print(matrix, vector)

[[0.4330201  0.95787159 0.50867057]
 [0.35225027 0.0110426  0.56063125]] [0.24525274 0.82270608 0.15464935]


In [ ]:
matrix.dot(vector)

array([0.97291172, 0.18217642])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[7 8]
 [3 7]] [[9 5]
 [7 6]]


In [ ]:
matrix_one*matrix_two

array([[63, 40],
       [21, 42]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[5 4]
 [8 2]] [[2 4]
 [6 4]]


In [ ]:
matrix_one.dot(matrix_two)

array([[34, 36],
       [28, 40]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix = np.random.randint(1, 100, (5,5))
print(matrix)

[[23 87 63 26  2]
 [ 5 40  5 19 72]
 [90 55 61 30 31]
 [20 18 46 79 33]
 [36 85 80 76 80]]


In [ ]:
matrix.sum()

1162

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix_one = np.random.randint(1, 10, (4,4))
matrix_two = np.random.randint(1, 10, (4,4))
print(matrix_one, matrix_two)

[[7 5 5 1]
 [2 3 3 9]
 [4 3 3 3]
 [4 2 1 9]] [[1 2 1 1]
 [9 1 8 4]
 [4 7 3 6]
 [9 7 1 8]]


In [ ]:
matrix_one-matrix_two

array([[ 6,  3,  4,  0],
       [-7,  2, -5,  5],
       [ 0, -4,  0, -3],
       [-5, -5,  0,  1]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [131]:
matrix = np.random.rand(3,3)
print(matrix)

[[0.97226408 0.68538036 0.78552854]
 [0.83743803 0.41311953 0.63301636]
 [0.24726646 0.08022025 0.52317763]]


In [132]:
matrix.shape[0]

3

In [145]:
np.array([matrix[i].sum() for i in range(matrix.shape[0])]).reshape(matrix.shape[0],1)

array([[2.44317298],
       [1.88357391],
       [0.85066434]])

In [138]:
matrix.sum(axis=1, keepdims=True)

array([[2.44317298],
       [1.88357391],
       [0.85066434]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [157]:
matrix = np.random.randint(1, 100, (3,4))
print(matrix)

[[17 64 17 21]
 [ 1 47 77 62]
 [62 33 10 59]]


In [158]:
np.square(matrix)

array([[ 289, 4096,  289,  441],
       [   1, 2209, 5929, 3844],
       [3844, 1089,  100, 3481]])

In [159]:
matrix*matrix

array([[ 289, 4096,  289,  441],
       [   1, 2209, 5929, 3844],
       [3844, 1089,  100, 3481]])

In [161]:
np.power(matrix, 2)

array([[ 289, 4096,  289,  441],
       [   1, 2209, 5929, 3844],
       [3844, 1089,  100, 3481]], dtype=int32)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [154]:
vector = np.random.randint(1, 50, 4)
print(vector)

[27  1 34 27]


In [155]:
np.sqrt(vector)

array([5.19615242, 1.        , 5.83095189, 5.19615242])

In [162]:
np.power(vector, 1/2)

array([5.19615242, 1.        , 5.83095189, 5.19615242])