In [42]:
import numpy as np

01. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [43]:
array = np.arange(0,10)
print(array)
array = np.array(range(10))
print(array)
array = np.linspace(0,9, num=10, dtype=int)
print(array)
array = np.asarray(range(0,10))
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


02. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [84]:
array_zero = np.zeros((3,3), dtype=int)
print(array_zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


03. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [45]:
array = np.random.randint(0, 10, (5,5))
print(array)

[[3 5 5 2 8]
 [1 6 6 7 8]
 [2 4 7 3 8]
 [7 4 6 5 4]
 [2 4 7 9 2]]


04. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [46]:
array = np.random.rand(4,4)
print(array)

[[0.67900335 0.64163497 0.20409539 0.05235306]
 [0.56749832 0.15619691 0.3332902  0.60540272]
 [0.85627259 0.9454706  0.86165493 0.38013329]
 [0.66090483 0.76933342 0.20877236 0.15758629]]


05. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [47]:
array_one = np.random.randint(1, 10, 5)
array_two = np.random.randint(1, 10, 5)
print(array_one, array_two)

[5 7 6 8 1] [7 9 4 2 4]


In [48]:
# Add 

print(array_one + array_two)

[12 16 10 10  5]


In [49]:
# Subtraction

print(array_one - array_two)

[-2 -2  2  6 -3]


In [50]:
# Multiplication

print(array_one * array_two)


[35 63 24 16  4]


In [51]:
# Devision

print(array_one / array_two)

[0.71428571 0.77777778 1.5        4.         0.25      ]


06. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [52]:
array_one = np.random.randint(1, 100, 7)
array_two = np.random.randint(1, 100, 7)
print(array_one, array_two)

print(list(zip(array_one, array_two)))

[77 24 27 31 13 12 84] [18 37 75 42 95 76 45]
[(77, 18), (24, 37), (27, 75), (31, 42), (13, 95), (12, 76), (84, 45)]


In [53]:
#
scalar = np.sum(array_one *array_two)
print(scalar)

np.dot(array_one, array_two)

11528


11528

07. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [54]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,3))

print(matrix_one, matrix_two)

[[3 5]
 [9 9]] [[8 3 5]
 [7 9 2]]


In [55]:
np.dot(matrix_one, matrix_two)

array([[ 59,  54,  25],
       [135, 108,  63]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [56]:
matrix = np.random.randint(1, 10, (3,3))
print(matrix)

[[4 8 7]
 [1 5 1]
 [3 9 5]]


In [57]:
np.linalg.inv(matrix)

array([[ 2.66666667,  3.83333333, -4.5       ],
       [-0.33333333, -0.16666667,  0.5       ],
       [-1.        , -2.        ,  2.        ]])

09. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [58]:
matrix = np.random.rand(4,4)
print(matrix)

[[0.84310723 0.11039013 0.50659407 0.86234804]
 [0.12493481 0.28163928 0.19631276 0.04497847]
 [0.35676168 0.35887951 0.15110165 0.87786766]
 [0.37315312 0.8854132  0.33906105 0.70550681]]


In [59]:
matrix.T

array([[0.84310723, 0.12493481, 0.35676168, 0.37315312],
       [0.11039013, 0.28163928, 0.35887951, 0.8854132 ],
       [0.50659407, 0.19631276, 0.15110165, 0.33906105],
       [0.86234804, 0.04497847, 0.87786766, 0.70550681]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [60]:
matrix = np.random.randint(1, 10, (3,4))
vector = np.random.randint(1, 10, 4)
print(matrix, vector)

[[4 9 5 4]
 [9 8 5 6]
 [9 3 1 7]] [5 8 9 4]


In [61]:
matrix.dot(vector)

array([153, 178, 106])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [62]:
matrix = np.random.rand(2,3)
vector = np.random.rand(3)
print(matrix, vector)

[[0.24890374 0.37351592 0.86664586]
 [0.12266498 0.14466036 0.66083954]] [0.80748659 0.12810274 0.89840568]


In [63]:
matrix.dot(vector)

array([1.02743441, 0.7112837 ])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [64]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[9 1]
 [5 8]] [[1 2]
 [4 2]]


In [65]:
matrix_one*matrix_two

array([[ 9,  2],
       [20, 16]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [66]:
matrix_one = np.random.randint(1, 10, (2,2))
matrix_two = np.random.randint(1, 10, (2,2))
print(matrix_one, matrix_two)

[[3 2]
 [2 7]] [[2 3]
 [2 4]]


In [67]:
matrix_one.dot(matrix_two)

array([[10, 17],
       [18, 34]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [68]:
matrix = np.random.randint(1, 100, (5,5))
print(matrix)

[[97 17 96  7 67]
 [31 96 90  8 96]
 [80 42 89 10 98]
 [48 58 91 83 45]
 [27 72 77 15 67]]


In [69]:
matrix.sum()

1507

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [70]:
matrix_one = np.random.randint(1, 10, (4,4))
matrix_two = np.random.randint(1, 10, (4,4))
print(matrix_one, matrix_two)

[[3 8 4 3]
 [6 1 6 4]
 [2 2 6 9]
 [9 6 2 5]] [[4 4 7 6]
 [3 4 6 1]
 [7 6 8 9]
 [2 5 3 8]]


In [71]:
matrix_one-matrix_two

array([[-1,  4, -3, -3],
       [ 3, -3,  0,  3],
       [-5, -4, -2,  0],
       [ 7,  1, -1, -3]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [72]:
matrix = np.random.rand(3,3)
print(matrix)

[[0.72014678 0.1564155  0.82770913]
 [0.14895346 0.94573844 0.63659489]
 [0.16586555 0.51554508 0.14548608]]


In [73]:
matrix.shape[0]

3

In [74]:
np.array([matrix[i].sum() for i in range(matrix.shape[0])]).reshape(matrix.shape[0],1)

array([[1.7042714 ],
       [1.73128678],
       [0.8268967 ]])

In [75]:
matrix.sum(axis=1, keepdims=True)

array([[1.7042714 ],
       [1.73128678],
       [0.8268967 ]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [76]:
matrix = np.random.randint(1, 100, (3,4))
print(matrix)

[[11 35 26 57]
 [43 53  9 27]
 [ 2 92 58 11]]


In [77]:
np.square(matrix)

array([[ 121, 1225,  676, 3249],
       [1849, 2809,   81,  729],
       [   4, 8464, 3364,  121]])

In [78]:
matrix*matrix

array([[ 121, 1225,  676, 3249],
       [1849, 2809,   81,  729],
       [   4, 8464, 3364,  121]])

In [79]:
np.power(matrix, 2)

array([[ 121, 1225,  676, 3249],
       [1849, 2809,   81,  729],
       [   4, 8464, 3364,  121]], dtype=int32)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [80]:
vector = np.random.randint(1, 50, 4)
print(vector)

[33  7 38 47]


In [81]:
np.sqrt(vector)

array([5.74456265, 2.64575131, 6.164414  , 6.8556546 ])

In [82]:
np.power(vector, 1/2)

array([5.74456265, 2.64575131, 6.164414  , 6.8556546 ])